In [3]:
class Classname:
 #some functions are variables
 #Function --- used to perform the specific activity
 #Variables ---data("memory")

SyntaxError: unexpected EOF while parsing (<ipython-input-3-f2b0cf39b21e>, line 4)

In [4]:
def test():
    return
test()

In [11]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return
obj=Demo()
obj.test()

test() for the class and method


In [13]:
class Demo1:
    def fact(self,n):
        #return the factorial
        fact = 1
        while(n!=0):
            fact = fact * n
            n = n-1
        return fact
p1 = Demo1()
print(p1.fact(5))

120


In [20]:
class Demo2:
 def __init__(self,p1,p2):
   self.p1=p1
   self.p2=p2
 def add(self,p1,p2):
   return p1+p2
 
c1=Demo2(10,20)
print(c1.add(100,200))
        

300


In [23]:
class Person(object):
    def __init__(self,name):
        self.name = name
    def getName(self):
        return self.name
    def isEmployee(self):
        return false    
class Employee(Person):
    def isEmployee(self):
        return true
emp = Person("Anil")
print(emp.getName(),emp.isEmployee())
emp1 = Employee("Akhil")
print(emp1.getName(),emp1.isEmployee())

NameError: name 'false' is not defined

In [26]:
lst =[1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [28]:
import numpy as np
lst=[1,2,3,4]
array = np.array(lst)
print(array)

[1 2 3 4]


In [29]:
lst=[1,2,3,4]
array = np.array(lst)
print(array)

[1 2 3 4]


In [31]:
lst = [1,2,3,4]
array = np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [33]:
lst = [1,4,5,6,7]
array = np.array(lst)
print(array.shape)
print(array.dtype)



(5,)
int32


In [35]:
a1 = np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [40]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [43]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [53]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]], dtype=int64)

In [54]:
A = np.matrix(np.ones((4,4),dtype=np.int64))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [55]:
a1=np.random.normal(5,0.5,10)
print(a1)


[5.13555439 4.79559614 4.50215516 5.25070446 5.27541049 4.9941349
 4.67504871 5.53756719 5.12021107 5.05219078]


In [56]:
a1 =np.array([(1,2,3),(4,5,6)])
print("Silicing column :",a1[:,1])

Silicing column : [2 5]


In [58]:
a1 =np.array([(1,2,3),(4,5,6)])
print("Silicing last column :",a1[:,2])

Silicing last column : [3 6]


In [59]:
a1 = np.random.normal(5,,1,10)
print(a1)
print("")

SyntaxError: invalid syntax (<ipython-input-59-5aea667f5c72>, line 1)

In [68]:
class Foo:
    def printline(self,line='python'):
        print(line)
o1 = Foo()
o1.printline("line")

line


In [74]:
import pandas as pd
dict = {"Name":["Anil","Akil"],
        "EMAIL ID":["anil01@gmail.com","akil22@gmail.com"],
        "MobileNumber":[9879787589,9989797988],
        "Adress":["Hyd","Hyd"]}
b= pd.DataFrame(dict)
print(b)
                    
                    
         

   Name          EMAIL ID  MobileNumber Adress
0  Anil  anil01@gmail.com    9879787589    Hyd
1  Akil  akil22@gmail.com    9989797988    Hyd


In [76]:
b.index = ["01","02"]
print(b)

    Name          EMAIL ID  MobileNumber Adress
01  Anil  anil01@gmail.com    9879787589    Hyd
02  Akil  akil22@gmail.com    9989797988    Hyd
